export const previewKey = [
  "Member ID",
  "Name of Applicant",
  "Parent Name ",
  "Phone Number",
  "Date Of Birth",
  "Gender",
  "Martial Status",
  "Pan Number",
  "Account Number",
  "IFSC Code",
  "Bank Name",
  "Address",
  "Name of the Nominee",
  "Relationship with Nominee",
  "Sponsor ID",
  "Applicant Placement Level",
  "Joining Date",
  "Joining Fee",
];
